### ISSUE TITLE
AttributeError: 'result' object has no attribute 'id'

### ISSUE THREAD

**Issue by tyler274** [gyllstromk/Flask-WhooshAlchemy#34]
Traceback (most recent call last):
  File "/Users/Tyler/Desktop/cookie/env/lib/python2.7/site-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/Users/Tyler/Desktop/cookie/env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/Tyler/Desktop/cookie/env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Tyler/Desktop/cookie/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Tyler/Desktop/cookie/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Tyler/Desktop/cookie/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Tyler/Desktop/cookie/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Tyler/Desktop/cookie/env/lib/python2.7/site-packages/flask_debugtoolbar/**init**.py", line 124, in dispatch_request
    return view_func(*_req.view_args)
  File "/Users/Tyler/Desktop/cookie/env/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(_args, *_kwargs)
  File "/Users/Tyler/Desktop/cookie/env/lib/python2.7/site-packages/flask_security/decorators.py", line 194, in decorated_view
    return fn(_args, *_kwargs)
  File "/Users/Tyler/Desktop/cookie/recruit_app/recruit_app/recruit/views.py", line 49, in application_queue
    recruiter_queue = HrApplication.query.whoosh_search('_' + str(search_form.search.data) + '*').paginate(page, current_app.config['MAX_NUMBER_PER_PAGE'], False)
  File "/Users/Tyler/Desktop/cookie/env/lib/python2.7/site-packages/flask_sqlalchemy/**init**.py", line 440, in paginate
    total = self.order_by(None).count()
  File "/Users/Tyler/Desktop/cookie/env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2734, in count
    return self.from_self(col).scalar()
  File "/Users/Tyler/Desktop/cookie/env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2513, in scalar
    ret = self.one()
  File "/Users/Tyler/Desktop/cookie/env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2482, in one
    ret = list(self)
  File "/Users/Tyler/Desktop/cookie/env/lib/python2.7/site-packages/flask_whooshalchemy.py", line 75, in **iter**
    self._primary_key_name))], row))
AttributeError: 'result' object has no attribute 'id'

relevant models found at https://github.com/tyler274/Recruitment-App/blob/master/recruit_app/user/models.py

**Comment by tyler274** [comment]
probably caused by issue #14
