### ISSUE TITLE
Error when import the module

### ISSUE THREAD

**Issue by karjok** [gyllstromk/Flask-WhooshAlchemy#70]
When i following <a href="https://youtu.be/bAPcmGNsulc">this tutorial</a>, i have error when importing the module.

```
>>> import flask_whooshalchemy
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/flask_whooshalchemy.py", line 18, in <module>                                 
import flask.ext.sqlalchemy as flask_sqlalchemy                    
ModuleNotFoundError: No module named 'flask.ext'                       
>>>
```

I running my script on termux

**Comment by dhamaniasad** [comment]
Please see #69
